[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
rand = "0.8.5"
scoped_threadpool = "0.1.*"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3