name: Render

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: High Quality Render
      run: cargo run --release -- 320 180 4096 5 scenes/box.json
    
    - uses: actions/upload-artifact@v3
      with:
        name: render-artifact
        path: |
          *.png
