name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --show-output
    - name: Render Test Image
      run: cargo run --release -- 256 256 256 5 scenes/cornell_box.json
    
    - uses: actions/upload-artifact@v3
      with:
        name: render-artifact
        path: |
          *.png
          renders/*.png
